# This is an "quick-look" highlighting test file just to see if everything feels and looks right
Stage One -> Stage Two -> Stage Three: repeat
b <-> c: "Reality is just a crutch for people who can't handle science fiction" {
  target-arrowhead: * {
    shape: diamond
    label: 1
    style.filled: true
    _.christmas.style.fill -> presents: regift
  }
  id: int {constraint: primary_key}
  id: int {constraint: [primary_key; foreign_key; unique; PK; FK; UNQ; random word]}
  number: -122
  float: -122.321
  boolean: true
  +publicVar: io.RuneReader
  -privateVar: d2ast.Position
  \#protectedMethod(n int): (s string, eof bool)
}
(x -> y)[0].style.stroke: red
explanation: |md
  # I can do headers
  1. test
|
explanation: |markdown
  # I can do headers
  1. test
|
formula: {
    equation: |latex
        \\lim_{h \\rightarrow 0 } \\frac{f(x+h)-f(x)}{h}
    |
}
explanation: |go
awsSession := From(c.Request.Context())
|
my_code: ||ts
  declare function getSmallPet(): Fish | Bird;
||
my_code: |||d2
  x: true || false
|||
my_code: |`ts
  const works = (a > 1) || (b < 2)
`|
...@people.management
x: @x.d2
x: @x
x: {
  ...@x.d2
}
x: @../y.d2
# test
"""test"""
test.*.test.*.test : label
test.**.test.**.test : label
test.***.test.***.test : label
t*st.*.t*st.*.t*st : label
