# Comment test

direction: down

Инициатор: {
  shape: sql_table
  ID: int {constraint: primary_key}
  ФИО: string
}

Инициатор <-> Заявка: Создаёт {
  source-arrowhead.shape: cf-one-required
  target-arrowhead.shape: cf-many
  style: {
    font-size: 24
    stroke-width: 4
  }
}

# Инициатор ----------------> Заявка

# Заявка: {
#   shape: sql_table
#   ID: int {constraint: primary_key}
#   ID ТипЗаявки: int {constraint: foreign_key}
#   ID Заказа: int {constraint: foreign_key}
#   ID Инициатора: int {constraint: foreign_key}
#   ID Согласователя: int {constraint: foreign_key}
#   Согласована: bool
#   Причина несогласования: string
#   Исполнена: bool
#   Приоритет: int
#   Количество: int
#   Товар: string
#   Вес (КГ): float
# }

# pg: PostgreSQL
# Cloud: my cloud
# Cloud.shape: cloud
# SQLite; Cassandra
