x
# <- @function

spaced string
#^^^^^^^^^^^^ @function

x.y
# <- @function
# ^ @function

_._
# <- @keyword
# ^ @keyword

3d
# <- @function.builtin

animated
# <- @function.builtin

bold
# <- @function.builtin

border-radius
# <- @function.builtin

class
# <- @function.builtin

classes
# <- @function.builtin

constraint
# <- @function.builtin

d2-config
# <- @function.builtin

direction
# <- @function.builtin

double-border
# <- @function.builtin

fill
# <- @function.builtin

fill-pattern
# <- @function.builtin

filled
# <- @function.builtin

font
# <- @function.builtin

font-color
# <- @function.builtin

font-size
# <- @function.builtin

height
# <- @function.builtin

italic
# <- @function.builtin

label
# <- @function.builtin

layers
# <- @function.builtin

link
# <- @function.builtin

multiple
# <- @function.builtin

near
# <- @function.builtin

opacity
# <- @function.builtin

scenarios
# <- @function.builtin

shadow
# <- @function.builtin

shape
# <- @function.builtin

source-arrowhead
# <- @function.builtin

steps
# <- @function.builtin

stroke
# <- @function.builtin

stroke-dash
# <- @function.builtin

stroke-width
# <- @function.builtin

style
# <- @function.builtin

target-arrowhead
# <- @function.builtin

text-transform
# <- @function.builtin

tooltip
# <- @function.builtin

underline
# <- @function.builtin

vars
# <- @function.builtin

width
# <- @function.builtin
