x: label
#  ^ @string

x: [one; two]
#   ^ @string
#        ^ @string

x: [primary_key; PK; foreign_key; FK; unique; UNQ; NULL; NOT NULL]
#   ^ @constant
#                ^  @constant
#                    ^  @constant
#                                 ^  @constant
#                                     ^  @constant
#                                             ^  @constant
#                                                  ^  @constant
#                                                        ^  @constant

x: |go var x = 5; |
#      ^ @string

x: 1
#  ^ @number

x: 1.1
#  ^ @number.float

x: true
#  ^ @boolean

x: false
#  ^ @boolean

x: null
#  ^ @keyword

x: Null
#  ^ @keyword

x: NULL
#  ^ @keyword

x: top-left
#  ^ @string.special

x: top-center
#  ^ @string.special

x: top-right
#  ^ @string.special

x: center-left
#  ^ @string.special

x: center-right
#  ^ @string.special

x: bottom-left
#  ^ @string.special

x: bottom-center
#  ^ @string.special

x: bottom-right
#  ^ @string.special

x: outside-top-left
#  ^ @string.special

x: outside-top-center
#  ^ @string.special

x: outside-top-right
#  ^ @string.special

x: outside-left-center
#  ^ @string.special

x: outside-right-center
#  ^ @string.special

x: outside-bottom-left
#  ^ @string.special

x: outside-bottom-center
#  ^ @string.special

x: outside-bottom-right
#  ^ @string.special
